### ISSUE TITLE
Unable to find/ Data/test_wiki5-1.json

### ISSUE THREAD

**Issue by ppzhr** [AONE-NLP/FSRE-SaCon#5]
When I execute bash run_train. sh, it shows that test_wiki5-1.json cannot be found. I don't see this file in the downloaded dataset. Could you please provide it?

“
5-way-1-shot Few-Shot Relation Classification
model: SimpleFSRE
encoder: bert
max_length: 128
We load /storage/zhr/FSRE-SaCon-main/fine-tune/ckpt/SaCon1 to train!
We load /storage/zhr/FSRE-SaCon-main/fine-tune/ckpt/SaCon2 to train!
path=========================
./data/test_wiki5-1.json
[ERROR] Data file does not exist!
Traceback (most recent call last):
  File "train.py", line 263, in <module>
    main()
  File "train.py", line 170, in main
    test_data_loader = get_loader22(opt.test, opt.pid2name, sentence_encoder,
  File "/storage/zhr/FSRE-SaCon-main/fine-tune/fewshot_re_kit/data_loader.py", line 269, in get_loader22
    dataset = FewRelTestDataset(name, pid2name, encoder, N, K, Q, root, ispubmed)
  File "/storage/zhr/FSRE-SaCon-main/fine-tune/fewshot_re_kit/data_loader.py", line 145, in __init__
    assert(0)
AssertionError
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/hyy/anaconda3/envs/FSRE_main/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/hyy/anaconda3/envs/FSRE_main/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hyy/anaconda3/envs/FSRE_main/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 49, in _pin_memory_loop
    do_one_step()
  File "/home/hyy/anaconda3/envs/FSRE_main/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 26, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/home/hyy/anaconda3/envs/FSRE_main/lib/python3.8/multiprocessing/queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "/home/hyy/anaconda3/envs/FSRE_main/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 305, in rebuild_storage_fd
    fd = df.detach()
  File "/home/hyy/anaconda3/envs/FSRE_main/lib/python3.8/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/hyy/anaconda3/envs/FSRE_main/lib/python3.8/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/hyy/anaconda3/envs/FSRE_main/lib/python3.8/multiprocessing/connection.py", line 508, in Client
    answer_challenge(c, authkey)
  File "/home/hyy/anaconda3/envs/FSRE_main/lib/python3.8/multiprocessing/connection.py", line 756, in answer_challenge
    response = connection.recv_bytes(256)        # reject large message
  File "/home/hyy/anaconda3/envs/FSRE_main/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/hyy/anaconda3/envs/FSRE_main/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/hyy/anaconda3/envs/FSRE_main/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
”

**Comment by Enronld** [comment]
We don't have permission to provide the test set. You can find the download URL in the readme file under the fine-tune folder.
fewrel1.0: https://codalab.lisn.upsaclay.fr/competitions/7395
fewrel2.0: https://codalab.lisn.upsaclay.fr/competitions/7397
